version: 2.1

jobs:
  build-test:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    environment:
      BUILDKIT_PROGRESS: 'plain'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-node-{{ .Branch }}
            - v1-node
      - run:
          name: Install packages
          command: npm ci --strict-peer-deps --ignore-scripts
      - save_cache:
          key: v1-node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          # TODO: chmod 777 isn't great, but the permission errors were getting too complicated
          name: Change project dir ownership to work in docker container
          command: |
            mkdir -p support/junit
            sudo chmod -R 'u=rwx,g=rwx,o=rwx' /home/circleci/project
      - run:
          name: Run tests
          command: |
            mkdir -p support/junit
            npm run test:clean
            npm test
      - store_test_results:
          path: support/junit
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  branch-build-test:
    jobs:
      - build-test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/

  tag-build-test-publish:
    jobs:
      - build-test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
